config/routes.rb
Rails.application.routes.draw do
  get "cards/search"
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  get "collection", to: "collection#index"

  root "home#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  before_create :set_uuid

  private

  def set_uuid
    return if self.class.attribute_types["id"].type != :uuid

    self.id ||= SecureRandom.uuid_v7
  end
end

app/models/card.rb
class Card < ApplicationRecord
  ACCESSIBLE_ATTRIBUTES = %i[name printed_name set set_name lang colors mana_cost cmc]

  ## Callbacks
  before_create :set_uuid_v7

  ## Store
  store_accessor :raw_data, *ACCESSIBLE_ATTRIBUTES

  ## Scopes
  # Returns a hash, where the keys are the names of the cards and the values are the cards themselves.
  def self.search(query)
    where("raw_data->>'name' ILIKE :query OR raw_data->>'printed_name' ILIKE :query", query: "%#{query}%")
      .group_by(&:name)
  end

  private

  def set_uuid_v7
    self.id = SecureRandom.uuid_v7
  end
end

app/models/collected_card.rb
class CollectedCard < ApplicationRecord
  belongs_to :user
  belongs_to :card

  delegate *%i[
    name
    printed_name
    set
    set_name
    lang
    colors
    mana_cost
    cmc
  ], to: :card
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :user_agent, :ip_address

  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user

  before_create do
    self.user_agent = Current.user_agent
    self.ip_address = Current.ip_address
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  ## Tokens
  generates_token_for :email_verification, expires_in: 2.days do
    email
  end
  generates_token_for :password_reset, expires_in: 20.minutes do
    password_salt.last(10)
  end

  ## Associations
  has_many :sessions, dependent: :destroy
  has_many :collected_cards, dependent: :destroy

  ## Validations
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 6 }

  ## Callbacks
  normalizes :email, with: -> { _1.strip.downcase }

  before_validation if: :email_changed?, on: :update do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_request_details
  before_action :authenticate

  private

  def authenticate
    if session_record = Session.find_by_id(cookies.signed[:session_token])
      Current.session = session_record
    else
      redirect_to sign_in_path
    end
  end

  def set_current_request_details
    Current.user_agent = request.user_agent
    Current.ip_address = request.ip
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def search
    @cards = Card.search(search_params[:query])
    render partial: 'cards/search_results', locals: { cards: @cards }
  end

  private

  def search_params
    params.permit(:query)
  end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  def index
    @collected_cards = Current.user.collected_cards.includes(:card)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "Your password has been changed"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_user
      @user = Current.user
    end

    def user_params
      params.permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session_record = @user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: session_record.id, httponly: true }

      #send_email_verification
      redirect_to root_path, notice: "Welcome! You have signed up successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.permit(:username, :email, :password, :password_confirmation)
    end

    def send_email_verification
      UserMailer.with(user: @user).email_verification.deliver_later
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: %i[ new create ]

  before_action :set_session, only: :destroy

  def index
    @sessions = Current.user.sessions.order(created_at: :desc)
  end

  def new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      @session = user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true }

      redirect_to root_path, notice: "Signed in successfully"
    else
      redirect_to sign_in_path(email_hint: params[:email]), alert: "That email or password is incorrect"
    end
  end

  def destroy
    @session.destroy; redirect_to(sessions_path, notice: "That session has been logged out")
  end

  private
    def set_session
      @session = Current.user.sessions.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(file)
    File.open("app/assets/images/#{file}.svg", "rb") do |file|
      raw file.read
    end
  end

  def bg_for_flash(key)
    case key
    when 'notice'
      'bg-teal-600'
    when 'alert'
      'bg-red-500'
    else
      'bg-gray-500'
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
  def display_name_for(card)
    if card.printed_name.present?
      return "#{card.name} (#{card.printed_name})"
    end

    card.printed_name.presence || card.name
  end
end

app/views/cards/_search_results.html.erb
<%# locals: (cards:) %>

<div>
  <h1>Cards found</h1>
  <ul>
    <% cards.each do |card| %>
      <li><%= card %></li>
    <% end %>
  </ul>
</div>

app/views/cards/search.html.erb
<div>
  <h1 class="font-bold text-4xl">Cards#search</h1>
  <p>Find me in app/views/cards/search.html.erb</p>
</div>

app/views/collection/index.html.erb
<div class="mb-8">
  <h1 class="font-bold text-4xl">Your collection</h1>
</div>

<div class="mt-8 overflow-x-auto rounded-md border border-gray-200">
  <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
    <thead class="text-left">
      <tr>
        <th class="whitespace-no-wrap px-4 py-2 font-medium text-gray-900">Name</th>
        <th class="whitespace-no-wrap px-4 py-2 font-medium text-gray-900">Set</th>
        <th class="whitespace-no-wrap px-4 py-2 font-medium text-gray-900">Mana cost</th>
        <th class="whitespace-no-wrap px-4 py-2 font-medium text-gray-900">Added at</th>
      </tr>
    </thead>

    <tbody class="divide-y divide-gray-200">
      <% @collected_cards.each do |cc| %>
        <tr>
          <td class="whitespace-no-wrap px-4 py-2 font-medium text-gray-900"><%= display_name_for(cc) %></td>
          <td class="whitespace-no-wrap px-4 py-2 text-gray-700">(<%= cc.set.upcase %>) <%= cc.set_name %></td>
          <td class="whitespace-no-wrap px-4 py-2 text-gray-700"><%= cc.mana_cost %></td>
          <td class="whitespace-no-wrap px-4 py-2 text-gray-700"><%= cc.created_at.strftime("%d %b, %Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<h1 class="text-3xl font-bold text-center">
  Hello, <%= Current.user.username %>
</h1>

app/views/home/old_home.html.erb
<p>Signed as <%= Current.user.username %></p>

<h2>Login and verification</h2>

<div>
  <%= link_to "Change password", edit_password_path %>
</div>

<div>
  <%= link_to "Change email address", edit_identity_email_path %>
</div>

<h2>Access history</h2>

<div>
  <%= link_to "Devices & Sessions", sessions_path %>
</div>

<br>

<%= button_to "Log out", Current.session, method: :delete %>

app/views/layouts/_footer.html.erb
<footer class="bg-teal-600 mt-8 py-4">
  <div class="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
    <div class="flex flex-col items-center justify-between py-4 md:flex-row">
      <div>
        <p class="text-xs text-white">Wizards of the Coast, Magic: The Gathering, and their logos are trademarks of Wizards of the Coast LLC in the United States and other countries. © 1993-2024 Wizards. All Rights Reserved.</p>
        <p class="text-xs text-white">© <%= Date.current.strftime("%Y") %> Grimoire</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-100">
  <div class="mx-auto max-w-screen-xl gap-4 sm:gap-6 lg:gap-8">
    <div class="flex h-16 items-center justify-between">
      <div class="flex-1 md:flex md:items-center md:gap-12">
        <a class="block text-teal-600" href="#">
          <span class="sr-only">Home</span>
          <%= svg('beholder') %>
        </a>
      </div>

      <div class="md:flex md:items-center md:gap-12">
        <nav aria-label="Global" class="hidden md:block">
          <ul class="flex items-center gap-6 text-sm">
            <% if Current.user %>
              <%= link_to "Collection", collection_path, class: "text-gray-500 transition hover:text-gray-500/75" %>
              <li>
                <a class="text-gray-500 transition hover:text-gray-500/75" href="#">Decks</a>
              </li>
              <li>
                <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> History </a>
              </li>
            <% end %>

            <li>
              <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Services </a>
            </li>

            <li>
              <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Projects </a>
            </li>

            <li>
              <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Blog </a>
            </li>
          </ul>
        </nav>

        <div class="flex items-center gap-4">
          <div class="sm:flex sm:gap-4">
            <% if Current.user %>
              <%= button_to "Logout", Current.session, method: :delete, class: "rounded-md bg-gray-100 px-5 py-2.5 text-sm text-teal-600" %>
            <% else %>
              <a
                class="rounded-md bg-teal-600 px-5 py-2.5 text-sm font-medium text-white shadow"
                href="#"
              >
                Login
              </a>

              <div class="hidden sm:flex">
                <a
                  class="rounded-md bg-gray-100 px-5 py-2.5 text-sm font-medium text-teal-600"
                  href="#"
                >
                  Register
                </a>
              </div>
            <% end %>
          </div>

          <div class="block md:hidden">
            <button class="rounded bg-gray-100 p-2 text-gray-600 transition hover:text-gray-600/75">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="size-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grimoire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script src="https://kit.fontawesome.com/40cb9d8c09.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <div class="<%= bg_for_flash(key) %> text-white p-4 text-center">
          <%= value %>
        </div>
      <% end %>
    <% end %>
    <main class="container mx-auto max-w-screen-xl mt-16 px-5 flex flex-col">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>